SECONDS_IN_DAY = 24 * 60 * 60
DAYS_IN_YEAR = 365.25

DAYOFWEEK_MONDAY = 0
DAYOFWEEK_TUESDAY = 1
DAYOFWEEK_WEDNESDAY = 2
DAYOFWEEK_THURSDAY = 3
DAYOFWEEK_FRIDAY = 4
DAYOFWEEK_SATURDAY = 5
DAYOFWEEK_SUNDAY = 6